# Generated by Django 2.1 on 2018-09-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0015_auto_20180912_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='site',
            field=models.CharField(max_length=128, unique=True, verbose_name='个人博客前缀'),
        ),
    ]
