# Generated by Django 2.1 on 2018-09-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0014_article_article_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='blog',
            field=models.ForeignKey(on_delete=None, to='repository.Blog', verbose_name='所属博客'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=None, to='repository.Category', verbose_name='文章类型'),
        ),
        migrations.AlterField(
            model_name='article2tag',
            name='article',
            field=models.ForeignKey(on_delete=None, to='repository.Article', verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='article2tag',
            name='tag',
            field=models.ForeignKey(on_delete=None, to='repository.Tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='articledetail',
            name='article',
            field=models.OneToOneField(on_delete=None, to='repository.Article', verbose_name='所属文章'),
        ),
        migrations.AlterField(
            model_name='category',
            name='blog',
            field=models.ForeignKey(on_delete=None, to='repository.Blog', verbose_name='所属博客'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=None, to='repository.Article', verbose_name='评论文章'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=None, related_name='back', to='repository.Comment', verbose_name='回复评论'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=None, to='repository.UserInfo', verbose_name='评论者'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='blog',
            field=models.ForeignKey(on_delete=None, to='repository.Blog', verbose_name='所属博客'),
        ),
        migrations.AlterField(
            model_name='updown',
            name='article',
            field=models.ForeignKey(on_delete=None, to='repository.Article', verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='updown',
            name='user',
            field=models.ForeignKey(on_delete=None, to='repository.UserInfo', verbose_name='赞或踩用户'),
        ),
        migrations.AlterField(
            model_name='userfans',
            name='follower',
            field=models.ForeignKey(on_delete=None, related_name='followers', to='repository.UserInfo', verbose_name='粉丝'),
        ),
        migrations.AlterField(
            model_name='userfans',
            name='user',
            field=models.ForeignKey(on_delete=None, related_name='users', to='repository.UserInfo', verbose_name='博主'),
        ),
    ]
