# Generated by Django 2.1 on 2018-09-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0016_auto_20180916_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='user',
            field=models.OneToOneField(on_delete=None, to='repository.UserInfo'),
        ),
    ]
