# Generated by Django 2.1 on 2018-08-16 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=32, unique=True)),
                ('ctime', models.DateTimeField(auto_now_add=True, null=True)),
                ('uptime', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=64, verbose_name='用户名')),
                ('password', models.CharField(help_text='pwd', max_length=32)),
                ('email', models.EmailField(max_length=32, null=True)),
                ('phone', models.CharField(max_length=32, null=True)),
                ('user_type_id', models.IntegerField(choices=[(1, '超级用户'), (2, '普通用户'), (3, '一般用户')], default=3)),
                ('user_group', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='usdb.UserGroup')),
            ],
        ),
    ]
