# Generated by Django 2.1 on 2018-08-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='用户名')),
                ('password', models.CharField(help_text='pwd', max_length=32)),
            ],
        ),
    ]
